### ISSUE TITLE
"Open Licence"

### ISSUE THREAD

**Issue by dimaursu** [emojidex/emojidex-legal-docs#1]
Your choice of words for the title of the license is at least misleading, and I hope it's not ill-intentioned.
The standard for getting the title of "open" is set here, http://opensource.org/definition , and your license doesn't match the definition on more that 50% of the points. The package under the current license is as proprietary as it can be, it's just gratis for certain usages. I think you should make that clear.

**Comment by Kagetsuki** [comment]
I think you have mis-read the license.

The open license allows usage equivalent to LGPL _for_ Open Source Software. The only parts that are heavily restricted are the image assets (which need these restrictions for preservation of copyright / protection of existing licensing agreements) and API access (to mitigate abuse) but even those can be used quite freely in OSS software without requiring any license modifications on said software. These terms are more "friendly" than say the GPL.

Furthermore, the license DOES fall under the guidelines of all points of the OSI definition - I was very particular about this when the license was written. Major restrictions only come in when you want to use the software in a closed-source commercial product. This is on purpose, as it both encourages people to open source their own software and it also prevents people from using the code and assets we have poured much of our lives into for their own profit with no mutual benefit.

Lastly, we haven't put up our mission statement yet as we haven't fully launched, but here is an excerpt:
"
      | The vast majority of profits from emojidex will go directly to supporting Open 
      | Software and Hardware development which attempt to make the future a better place 
      | for all of us. We want you to know that when you pay for anyting on emojidex you're 
      | not supporting a huge profit-oriented corporation; you're supporting a small team 
      | of struggling developers who love science, technology and Open Source and want to 
      | use them to make a better future for our children.
"
I seriously hope you consider editing your comment or deleting this issue. I have dedicated an immense amount of my life and many times much of my personal income to Open Source. I take great offence at you accusing my intentions to be in-genuine.

**Comment by dimaursu** [comment]
Oh, it has a dual license. Sorry about that, I haven't noticed the file with the `General License Terms and Conditions`. Unfortunately I can't delete the Issue myself. If you can do it, please do so. I won't edit the issue, as the rest of the conversation would not make sense anymore. 
My apologies.

**Comment by Kagetsuki** [comment]
@dimaursu No problem. Now that you mention it I forgot to explicitly link the General License and Open License so it is hard to understand they are two parts of the same thing and somebody could certainly miss something.

Of course we absolutely are open to criticism of any of our License. If you find fault with a specific point in the license PLEASE do not hesitate to specify. And if you are in need of an amendment to the license for something specific please feel free to contact me directly to discuss this.

Regardless, thanks for your interest in our project! I sincerely hope you will find a place for it in your software works - OSS or otherwise :+1: 

*I'll leave the issue here for a bit unless you want me to delete it right away. It is possible other people could have had the same misunderstanding.
